### ISSUE TITLE
Failed to open BuildTools\control\control.nacp!

### ISSUE THREAD

**Issue by Mini-Placzek** [StarDustCFW/SimpleNSPForwader#1]
I'm trying to get a working NSP forwarder since most of them are broken on FW 12.0.X and your solution looked very promising. I tried both of your methods the hta based GUI and the batch version. Both won't give me a NSP and I'm pretty sure it has to do with this error. Maybe there are additional steps needed you didn't mention or there is something missing from your repository. 
Great work so far btw :)
![image](https://user-images.githubusercontent.com/26483105/119534524-4fae7500-bd87-11eb-8d3c-0077a5760c18.png)

**Comment by Kronos2308** [comment]
your title id is to big

**Comment by Kronos2308** [comment]
16 caracters
05B80C7D3B860000 
wit the 05 before and the 000 after

**Comment by Kronos2308** [comment]
https://github.com/StarDustCFW/SimpleNSPForwader/archive/refs/heads/main.zip
listo esta arreglado

**Comment by Mini-Placzek** [comment]
Works perfectly fine now. Thanks
